//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.06.25 at 04:29:59 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dsg.ce.unipr.it/software/deus/schema/automator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.unipr.ce.dsg.deus.schema;
