//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.21 at 11:21:04 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dsg.ce.unipr.it/software/deus/schema/automator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.unipr.ce.dsg.deus.schema;
